// C++ program to demonstrate working of unnamed
//unnamed namespaces
/*
 *They are directly usable in the same program and are used for declaring unique identifiers.

 In unnamed namespaces, name of the namespace in not mentioned in the declaration of namespace.

 The name of the namespace is UNIQUELY  generated by the compiler.

 The unnamed namespaces you have created will only be accessible within the file you created it in.
 
 Unnamed namespaces are the REPLACEMENT for the static declaration of variables.

*/

#include <iostream>

using namespace std;

// unnamed namespace declaration
namespace
{
int rel = 300;
}
namespace 
{
	float t = rel++;
}

int main()
{
cout << rel << "\n"; // prints 300
cout << t << endl;
cout << rel << endl;
return 0;
}

